version: '3.6'
services:
  discordbot:
    build:
      context: docker/nodejs/docker-dev
      dockerfile: Dockerfile
    image: nodejs-dev:20-alpine
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
    volumes:
      - ./config:/workspace/dist/config:delegated
    ports:
      - "4000:4000"
    networks:
      - bot-network

  redis:
    image: redis:alpine
    # volume for redis data
    volumes:
      - ./redis-data:/data
    # Make sure redis saves snapshots to disk
    command: redis-server --appendonly yes
    networks:
      - bot-network

  mongodb:
    image: mongo:7.0.8
    volumes:
      - ./mongo-data:/data/db
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
